<?php
/**
 * @var Smile\ElasticsuiteAnalytics\Block\Adminhtml\Search\Usage\ChartInterface $block
 */

$chartContainerId = $block->getJsId();
$chartType = $block->getChartType() ?: 'PieChart';
?>
<div class="dashboard-item">
    <div class="dashboard-item-title"><?= $block->getTitle() ;?></div>
    <div class="dashboard-item-content">
        <div id="<?= $chartContainerId ?>" style="min-height:300px"></div><!-- style="width: 900px; height: 500px;"></div> -->
    </div>
</div>
<script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(function () {
        var data = new google.visualization.DataTable(<?= json_encode($block->getChartData()) ?>);

        var options = <?= $block->getChartOptions() ?>;

        var chart = new google.visualization.<?= $chartType ?>(document.getElementById('<?= $chartContainerId ?>'));

        chart.draw(data, options);
    });
</script>
